module.exports = {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-order"],
  rules: {
    "property-no-vendor-prefix": null,
    "value-keyword-case": null,
    "media-feature-range-notation": null,
    "no-duplicate-selectors": null,
    "import-notation": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "no-descending-specificity": null,
    "color-function-notation": null,
    "hue-degree-notation": null,
    "custom-property-empty-line-before": null,
    "color-function-alias-notation": null,
    "alpha-value-notation": null,
    "selector-pseudo-class-no-unknown": [
      true,
      {
        ignorePseudoClasses: ["global"],
      },
    ],
    "declaration-empty-line-before": null,
    "order/properties-order": [
      [
        {
          groupName: "layout",
          emptyLineBefore: "never",
          properties: [
            "display",
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "float",
            "clear",
            "flex",
            "flex-direction",
            "flex-wrap",
            "flex-flow",
            "justify-content",
            "align-items",
            "align-content",
            "align-self",
            "order",
            "grid",
            "grid-template",
            "grid-template-columns",
            "grid-template-rows",
            "grid-template-areas",
            "grid-auto-columns",
            "grid-auto-rows",
            "grid-auto-flow",
            "grid-column",
            "grid-row",
            "gap",
            "column-gap",
            "row-gap",
          ],
        },
        {
          groupName: "spacing",
          emptyLineBefore: "never",
          properties: [
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
          ],
        },
        {
          groupName: "sizing",
          emptyLineBefore: "never",
          properties: [
            "width",
            "min-width",
            "max-width",
            "height",
            "min-height",
            "max-height",
            "box-sizing",
          ],
        },
        {
          groupName: "typography",
          emptyLineBefore: "never",
          properties: [
            "font",
            "font-family",
            "font-size",
            "font-weight",
            "font-style",
            "font-variant",
            "line-height",
            "letter-spacing",
            "text-align",
            "text-decoration",
            "text-transform",
            "text-indent",
            "text-overflow",
            "white-space",
            "word-break",
            "word-wrap",
            "color",
          ],
        },
        {
          groupName: "visual",
          emptyLineBefore: "never",
          properties: [
            "background",
            "background-color",
            "background-image",
            "background-repeat",
            "background-position",
            "background-size",
            "border",
            "border-top",
            "border-right",
            "border-bottom",
            "border-left",
            "border-width",
            "border-style",
            "border-color",
            "border-radius",
            "box-shadow",
            "opacity",
            "visibility",
          ],
        },
        {
          groupName: "misc",
          emptyLineBefore: "never",
          properties: [
            "cursor",
            "overflow",
            "overflow-x",
            "overflow-y",
            "transition",
            "transform",
            "animation",
          ],
        },
      ],
      {
        severity: "warning",
      },
    ],
    "custom-property-pattern": null,
  },
  ignoreFiles: ["**/node_modules/**", "**/.next/**", "**/dist/**"],
};
