<?php

namespace Stripe\StripeTaxForWooCommerce\SDK\lib\Util;

class ObjectTypes {

	/**
	 * @var array Mapping from object types to resource classes
	 */
	const mapping =
		array(
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Collection::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Collection::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\CardDetails::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\CardDetails::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SearchResult::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SearchResult::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\File::OBJECT_NAME_ALT => \Stripe\StripeTaxForWooCommerce\SDK\lib\File::class,
			// The beginning of the section generated from our OpenAPI spec
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Account::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Account::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\AccountLink::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\AccountLink::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\AccountSession::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\AccountSession::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\ApplePayDomain::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\ApplePayDomain::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\ApplicationFee::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\ApplicationFee::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\ApplicationFeeRefund::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\ApplicationFeeRefund::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Apps\Secret::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Apps\Secret::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Balance::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Balance::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\BalanceTransaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\BalanceTransaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\BankAccount::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\BankAccount::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\BillingPortal\Configuration::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\BillingPortal\Configuration::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\BillingPortal\Session::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\BillingPortal\Session::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Capability::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Capability::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Card::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Card::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CashBalance::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CashBalance::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Charge::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Charge::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Checkout\Session::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Checkout\Session::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Order::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Order::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Product::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Product::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Supplier::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Climate\Supplier::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CountrySpec::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CountrySpec::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Coupon::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Coupon::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CreditNote::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CreditNote::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CreditNoteLineItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CreditNoteLineItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Customer::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Customer::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CustomerBalanceTransaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CustomerBalanceTransaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\CustomerCashBalanceTransaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\CustomerCashBalanceTransaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Discount::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Discount::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Dispute::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Dispute::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\EphemeralKey::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\EphemeralKey::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Event::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Event::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\ExchangeRate::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\ExchangeRate::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\File::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\File::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FileLink::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FileLink::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Account::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Account::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\AccountOwner::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\AccountOwner::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\AccountOwnership::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\AccountOwnership::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Session::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Session::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Transaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FinancialConnections\Transaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\FundingInstructions::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\FundingInstructions::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Identity\VerificationReport::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Identity\VerificationReport::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Identity\VerificationSession::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Identity\VerificationSession::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Invoice::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Invoice::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\InvoiceItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\InvoiceItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\InvoiceLineItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\InvoiceLineItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Authorization::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Authorization::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Card::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Card::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Cardholder::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Cardholder::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Dispute::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Dispute::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Token::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Token::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Transaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Issuing\Transaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\LineItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\LineItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\LoginLink::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\LoginLink::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Mandate::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Mandate::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentIntent::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentIntent::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentLink::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentLink::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethod::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethod::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethodConfiguration::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethodConfiguration::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethodDomain::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PaymentMethodDomain::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Payout::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Payout::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Person::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Person::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Plan::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Plan::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Price::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Price::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Product::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Product::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\PromotionCode::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\PromotionCode::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Quote::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Quote::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\EarlyFraudWarning::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\EarlyFraudWarning::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\ValueList::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\ValueList::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\ValueListItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Radar\ValueListItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Refund::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Refund::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Reporting\ReportRun::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Reporting\ReportRun::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Reporting\ReportType::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Reporting\ReportType::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Review::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Review::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SetupAttempt::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SetupAttempt::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SetupIntent::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SetupIntent::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\ShippingRate::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\ShippingRate::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Sigma\ScheduledQueryRun::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Sigma\ScheduledQueryRun::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Source::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Source::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SourceTransaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SourceTransaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Subscription::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Subscription::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SubscriptionItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SubscriptionItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\SubscriptionSchedule::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\SubscriptionSchedule::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Calculation::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Calculation::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\CalculationLineItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\CalculationLineItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Registration::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Registration::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Settings::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Settings::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Transaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\Transaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\TransactionLineItem::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Tax\TransactionLineItem::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\TaxCode::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\TaxCode::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\TaxId::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\TaxId::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\TaxRate::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\TaxRate::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Configuration::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Configuration::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\ConnectionToken::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\ConnectionToken::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Location::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Location::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Reader::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Terminal\Reader::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\TestHelpers\TestClock::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\TestHelpers\TestClock::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Token::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Token::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Topup::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Topup::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Transfer::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Transfer::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\TransferReversal::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\TransferReversal::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\CreditReversal::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\CreditReversal::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\DebitReversal::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\DebitReversal::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\FinancialAccount::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\FinancialAccount::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\FinancialAccountFeatures::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\FinancialAccountFeatures::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\InboundTransfer::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\InboundTransfer::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\OutboundPayment::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\OutboundPayment::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\OutboundTransfer::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\OutboundTransfer::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\ReceivedCredit::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\ReceivedCredit::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\ReceivedDebit::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\ReceivedDebit::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\Transaction::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\Transaction::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\TransactionEntry::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\Treasury\TransactionEntry::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\UsageRecord::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\UsageRecord::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\UsageRecordSummary::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\UsageRecordSummary::class,
			\Stripe\StripeTaxForWooCommerce\SDK\lib\WebhookEndpoint::OBJECT_NAME => \Stripe\StripeTaxForWooCommerce\SDK\lib\WebhookEndpoint::class,
			// The end of the section generated from our OpenAPI spec
		);
}
