export const wordpressConfig = {
  graphqlEndpoint: process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || "",
  revalidationTime: 60,
  enabledPostTypes: ["page", "post"],
  enabledMenus: ["main-menu", "footer-menu"],
  customFields: {
    customSEO: true,
    redirection: true,
    scripts: true,
    upperFooter: true,
    lowFooter: true,
    intro: true,
    galleryPage: true,
    blox: true,
    cta: true,
  },
  imageDomains: [
    "lh3.googleusercontent.com",
    "nfcpt.ts",
    "old.northfloridachiropracticphysicaltherapy.com",
    "www.northfloridachiropracticphysicaltherapy.com",
    "res.cloudinary.com",
    "localhost:3000",
    "localhost:8080",
    "images.unsplash.com",
  ],
} as const;
